### ISSUE TITLE
CAP splitLeg function

### ISSUE THREAD

**Issue by AlerantAppNGIN** [RestComm/jss7#105]
SpiltLeg handling is missing from CAPServiceCircuitSwitchedCall.

**Comment by vetss** [comment]
Hello @AlerantAppNGIN,

this issue is partly fixed by commits:
https://github.com/RestComm/jss7/commit/32ee08abe381a9f10706a0dbb01e239681dee02c
https://github.com/RestComm/jss7/commit/a859326bc1e4d130ab3e1a365d32fc7abffab2b1
https://github.com/RestComm/jss7/commit/5f7e0579ea120c5de838a05010216d4fb63b9387

These commits are added into netty-2 branch because we stopped of adding more fixes into a master branch. We will rename netty-2 branch to master branch soon. netty-2 branch contains some extra functionality including netty lib and congestion control support support.

What is still missed:
- we need to add unit tests for SplitLegRequest and SplitLegResponse primitives including a test for XML serializing
- we need to add CAP Functional test for the introduced CAP SplitLeg operation.

@AlerantAppNGIN can you finish this work ?

**Comment by vetss** [comment]
We need also to update CAP RA for this new operation:
https://github.com/RestComm/jain-slee.ss7/issues/9
