### ISSUE TITLE
CAP Apply Charging handling improvments

### ISSUE THREAD

**Issue by AlerantAppNGIN** [RestComm/jss7#115]
Hello,

I extracted some mods from our fork here is the description of modifications and I'll also send a PR which makes things even clearer :-) 

Description: 
- Added concrete CAP version to InitialDP instead of "isCapVersion3OrLater".
- Fixed LegID encoding in AChChargingAddress.
- Improved CAP phase (3-4) handling in CAMELAchBillingChargingCharacteristicsImpl by replacing "isCap3OrLater" with explicit CAP version.
  - Changed XML serialization to honor the default value of legActive the same way as the ASN.1 encoding does.
  - Modified CAPFuntionalTest to use the default values pf AChChargingAddress in AChBillingChargingCharacteristics and TimeDuration objects
  - Modified ApplyChargingRequestTest to use the default values of the partyToCharge
    and AChChargingAddresses fields
  - In the AudibleIndicatorTest a new test case is added to both the decode and the encode test methods
  - In the CAMELAChBillingChargingCharacteristicsTest a new test case is addded to bothe the decode and encode methods and fixed the encoding/decoding of the AudibleIndicator field.
  - In the testDecode method of TimeDurationChargingResultTest fixed the handling of AChChargingAddress field.

Regards,
Gabor

**Comment by vetss** [comment]
Hello @AlerantAppNGIN 

thank you for provided update in https://github.com/RestComm/jss7/pull/116. I have not committed it fully (it is little bit complicated) but created a cunulative commit for code updates that we can accept:
https://github.com/RestComm/jss7/commit/8836b0379a706955cea6bd574c3c0880f06ae386

My comments:

1) thank you for a catch and provided code for wrong implemented CAMELAchBillingChargingCharacteristicsImpl. I include most of your code but with several changes for minimizing of changes. Please check my update.

2) When we were implementing primitives like "BOOLEAN DEFAULT FALSE" (with default) values we thought of two type of options: 
a) decode just what has come from a peer and let a CAP user use of some default value if a parameter is null 
b) fill a default value at the step of decoding
We decided to follow "a)" way so not filling of any default value. The same we do at XML serializing. Let's not change existing behavior as much as it possible. The same if for "Added concrete CAP version to InitialDP instead of "isCapVersion3OrLater"." - I have not added this update in order not to breake current behaviour.

**Comment by gsaslis** [comment]
@knosach is this closed as invalid nowadays, or fixed?

**Comment by knosach** [comment]
hi @gsaslis it was fixed
