### ISSUE TITLE
ApplicationContextName of non activated MAPService

### ISSUE THREAD

**Issue by jeenareload** [RestComm/jss7#161]
Hi,
I have deploy ussdgateway and update Sub System Number 7 in TCAP , TCAP stack is running success, But i receive ABORT message while sending PSSR request ussdgateway.

[trace.zip](https://github.com/RestComm/jss7/files/444066/trace.zip)

10:41:57,638 WARN  [MAPStackImpl-MapStack] ApplicationContextName of non activated MAPService is received. Will send back TCAP Abort : 0, 4, 0, 0, 1, 0, 19, 2,

**Comment by vetss** [comment]
Hello @jeenareload 

1) your question looks more as configuring case. You can ask questions in a forum
https://groups.google.com/forum/?utm_source=digest&utm_medium=email#!forum/restcomm
because it may most probably not a product issue.

2) you have mentioned ussd GW. Do you mean this project: https://github.com/RestComm/ussdgateway ?

3) To avoid this "ApplicationContextName of non activated MAPService" you need to activate a needed service (ussd service I guess if you mention) with invoke like:
MAPServiceSupplementaryImpl.acivate()

But if you use USSD GW or deploy MAP RA into jboss, this is made by default.

**Comment by jeenareload** [comment]
Hi @vetss ,

Yes I mean project: https://github.com/RestComm/ussdgateway ? 
I am using  USSD GW, I build it from source but facing same issue, I have changed SSN from 8 to 7. (bcz i need SSN 7)

Can you please tell me where MAPServiceSupplementaryImpl.acivate() is invoked in  USSD source code  ??

**Comment by vetss** [comment]
I am closing this issue because it is for another project (ussd gw)
