### ISSUE TITLE
NullpointerException is occured during loadActualData of M3UA configuration

### ISSUE THREAD

**Issue by Peramuthan** [RestComm/jss7#179]
Hi All, 
In  both jSS7 stack 7.1.1385 and 7.0.1383 versions having this issue.

file name: M3UAManagementImpl.java

 private void loadActualData(XMLObjectReader reader ) throws XMLStreamException, IOException{
        try {
//          this.maxSequenceNumber = reader.read(MAX_SEQUENCE_NUMBER_PROP, Integer.class);
//          this.maxAsForRoute = reader.read(MAX_AS_FOR_ROUTE_PROP, Integer.class);
          Integer vali = reader.read(MAX_SEQUENCE_NUMBER_PROP, Integer.class);
          **vali = reader.read(MAX_AS_FOR_ROUTE_PROP, Integer.class);**

          this.timeBetweenHeartbeat = reader.read(HEART_BEAT_TIME_PROP, Integer.class);
      } catch (java.lang.Exception e) {
          // ignore.
          // For backward compatibility we can ignore if these values are not defined
          logger.error("Errro while reading attribute", e);
      }
     --

}
 
Bolded statement is try to read the "maxasforroute" value from XML file. but no where writing this value in XML file. 

Please correct this error in latest release.

Thanks & Regards,
Peramuthan Rameshkumar

**Comment by vetss** [comment]
@Peramuthan 

We need to check - if we use the parameter and it is needed to be stored we can add it.

**Comment by deruelle** [comment]
@vetss did you check that ? Can @Peramuthan take ownership of this one ?

**Comment by vetss** [comment]
@deruelle 

I have not checked it yet, sorry.

**Comment by vetss** [comment]
Hello @Peramuthan 

Sorry for delayed response (this issue is minor). There are some parameters for m3ua stack that are not stored in xml files but is needed to configure by setters. And mentioned parameters are also not stored into xml files. What you see is some stabs that prevern of old format sml files reading (before such parameters were present in xml configs). So please do not change code, it is correct.

You can check such parameters list for stacks in the file:
https://github.com/RestComm/jss7/blob/master/Stacks_Parameters.ods
You can find info there which parameters are stored into xml and which are not.
Anyway, @Peramuthan  thanks for seaching bugs in jss7 stack.

I am closing the issue.
