### ISSUE TITLE
Server Example Code

### ISSUE THREAD

**Issue by princebayan** [RestComm/jss7#222]
I was wondering if there are any example code (java) working as server and in the jss7 (web) i will configure it as client? 
you have posted a client code example.. and i have used it before but now i need a code as a server side ... please help.

**Comment by vetss** [comment]
Hello @princebayan 

Sorry for delayed response. Examples of code (both client and server side) you can find in https://github.com/RestComm/jss7/tree/master/map/load

Possibly you have asked for something else because you mentioned "web". I do not fully understand what you need.

Github issues set is more for discussin of bugs and needed functionality. You can ask questions in community forums like:
https://groups.google.com/forum/?utm_source=digest&utm_medium=email#!forum/restcomm

**Comment by knosach** [comment]
closed due to inactivity
