### ISSUE TITLE
SLS should support odd or even number

### ISSUE THREAD

**Issue by nhanth87** [RestComm/jss7#223]
Oracle Communication has supported SLS odd and even for ss7 load balancing.
jss7 shoud have configuration for sls odd or even to adap it

https://www.dialogic.com/den/developer_forums/f/10/t/7280.aspx

**Comment by faizann** [comment]
Hi

I thought Bit0 Algorithm for loadsharing does it already.

**Comment by nhanth87** [comment]
Hi @faizann, we need configuration so the ss7 application is only send and receive with odd or even

Br,
TN

**Comment by nhanth87** [comment]
if you config bit0 then you can't control if you just want to receive odd or even SLS

**Comment by faizann** [comment]
Understood.  So, in what cases someone needs such a configuration?

**Comment by nhanth87** [comment]
hi @faizann in case of 2 ss7 application running replication with STP is Oracle Communication.
this fix is a part of https://github.com/RestComm/jss7/issues/219

Br,
TN

**Comment by deruelle** [comment]
Can we close this issue since it's fixed in #219 ?

**Comment by vetss** [comment]
@deruelle 

https://github.com/RestComm/jss7/issues/219 - is the issues for another case (m3ua). This issues is for TCAP stack. @nhanth87 need to provide configuring part to finish this case.

**Comment by vetss** [comment]
Hi @nhanth87 

1) I have committed you fix inti non-netty branch. So we can build binaries and thest them at a customer side.
2) I have added one little fix for the following reason: 
XML serializing / deserializing does now work fine if we add some new items at the end of the file because if internal algo reason. We need to follow a rule that if we update a list of items we need to add them in the middle, not at the end. Please follow this rule further.
3) It is better to have in CLI interface not digital parameters but strings like "odd", "even", "all". It is not a critical issue but it is better to fix it. You can reuse some enum in configuring.
4) it not a good way to add a special branch into a repo https://github.com/RestComm/jss7 for so little fix. Better if you create a branch in your repo (that was forked after). Please remove the branch in "RestComm" after we finish of this fix.
5) We need to update also master branch.

@nhanth87 do you have a write access to repos ?

**Comment by vetss** [comment]
Fixed in non-netty branch by:
https://github.com/RestComm/jss7/commit/105b8a1fd51f8e3a2af804d341af46ccb46ea3da
https://github.com/RestComm/jss7/commit/df448c2959095f6843baa9cf31ac95b42ab51af3
https://github.com/RestComm/jss7/commit/5fa274bc27f9ebda05a43652440f3e12bcd35219
https://github.com/RestComm/jss7/commit/90c387430209333bcb4517fae8e2a2ef31876910
https://github.com/RestComm/jss7/commit/ef97d3c6e90d6a640bb816d1b38e61422981b406

Fixed in master branch:
https://github.com/RestComm/jss7/commit/c213ac942a33edfddcdc2bf3cffbe2d8ccaffcdd
https://github.com/RestComm/jss7/commit/11959c7ccb973eb9af753b9c1aaddab31b261d75
https://github.com/RestComm/jss7/commit/6c96a6c0ee234de0e52c138637359a05f303b4c8
https://github.com/RestComm/jss7/commit/19e30112c0daec41b5eb7bfd999805961e1c5a2f
https://github.com/RestComm/jss7/commit/2a7233654d7b789e326e24770048eb9d2accb454
https://github.com/RestComm/jss7/commit/85fbb1a31180680e5858b912d375323c83c80d99

Thanks for your updates @nhanth87
