### ISSUE TITLE
Change references to com.telscale and TelScale

### ISSUE THREAD

**Issue by deruelle** [RestComm/jss7#27]
there is a lot of com.telscale packages as seen in 
https://github.com/RestComm/jss7/search?utf8=%E2%9C%93&q=com.telscale
we need to change those to org.mobicents to be consistent and remove references to TelScale in general and only keep Mobicents or restcomm now that the brand is changing http://www.telestax.com/restcomm-moves-beyond-mobicents/

**Comment by vetss** [comment]
Fixed by:
https://github.com/RestComm/jss7/commit/50614dba376caa577ec290140ee01dbd9fec4d60
https://github.com/RestComm/jss7/commit/4b61d66d3c610b294a3e98581820c1c9350c73a1
https://github.com/RestComm/jss7/commit/93002aba73921aaecebc192b17ef14da03676000
https://github.com/RestComm/jss7/commit/4b571486e7957383d552ffbeeb57e5f8c666cfb1
