### ISSUE TITLE
MAP error msg : facilitynotsupp

### ISSUE THREAD

**Issue by terminator102** [RestComm/jss7#284]
Whenever SMSC receives msg from remote SMSC, it returns following error: 

`Home routing: Sent ErrorComponent = MAPErrorMessageFacilityNotSup []`

why is this? I am running old setup which was working fine few days back.

**Comment by knosach** [comment]
Hi @terminator102 
this issue related to config of SMSC (not JSS7 stack). this occurs when HrCharging set to [reject](https://github.com/RestComm/smscgateway/blob/4360679147feb912e89d6cdb5c3dfe8087d79489/core/slee/services/homeroutingsbb/src/main/java/org/mobicents/smsc/slee/services/hr/HrSriServerSbb.java#L175).
In case of customer support and 24/7. I think you should request a professional support instead of waiting for community support.
You can request it from https://accounts.restcomm.com/registration.jsp
