### ISSUE TITLE
Licensing not clear

### ISSUE THREAD

**Issue by cedricOL** [RestComm/jss7#321]
Hello,

I found the licensing information not clear, AGPL is stated on root of the project and in github, but many of the sources are LGPL header. Plus commercial license is available.
Can you clarify in the documentation the boundaries of each licences?

Thank You
Cedric

**Comment by yulianoifa-mobius** [comment]
Hi The License is AGPL license for the project. However due to historical reason ( files that was not changed after license modification ) some files has been kept LGPL
The commercial license allows to use commercial release with some additional features and additionally with support options

**Comment by cedricOL** [comment]
Hi I think you must modify header of files, notify every contributor of this (and maybe get acceptation of them) (but it is private to your processes).
If you do not do so, anyone can pretend the they are using the LGPL version as written in the source file. Especially that it looks that it is for specific component only.

**Comment by yulianoifa-mobius** [comment]
@cedricOL thanks for the comments. Each file contants the list of authors. Additionally each contributor signed contribution/agreement with their acceptance. However legal terms are : we can modify license for any single java file changed, and we can't for any file that was not changed by Telestax/partners teams. Licenses rules are defining that highest license used should be the defining one, so legally code can not be used as LGPL. Practically of course it can be done... 
In any case newcoming versions ( either commercial or open source -> which is currently negotiated with Telestax ) would have most of files modified due to structure , parsers and params rework. As result this question would not be relevant
