### ISSUE TITLE
CAPDialog CAPTimer handling mod

### ISSUE THREAD

**Issue by AlerantAppNGIN** [RestComm/jss7#85]
Type: Enhancement
Issue short: Modify CAPDialog CAPTimer handling to allow customization and to eliminate interface constants pattern

Description: The default value of CAP timers are encapsulated in the new CAPTimerDefault class which can be modified (extend) and set to CAP stack instances

**Comment by vetss** [comment]
Hello @AlerantAppNGIN,

your provide solution is needed for sure for JSS7 stack. We have a special issue for adding of InvokeTimeout parameters: https://github.com/RestComm/jss7/issues/66 (please check it).

But we need to follow some style by which we can use for parameters configuring in jboss-beans.xml and by CLI / GUI interface or by JMX invokes (when usage of a SLEE mode, not a stand-alone mode). Check how we implement "invokeTimeout" parameter for TCAPStack. We need something like this fr CAP timeouts too.

So CAPStack must contain getters and setters like:
long getTimerCircuitSwitchedCallControlShort getTimerCircuitSwitchedCallControlShort();
setTimerCircuitSwitchedCallControlShort(long value);

Providing of CLI / GUI is a task for future because we have not implemented CLI / GUI interfaces for MAP / CAP.

Can you please update your patch so it fits those requirenments (for MAP and CAP stacks) ?

**Comment by knosach** [comment]
will be implemented as part in #66
