### ISSUE TITLE
Map implementation fixes

### ISSUE THREAD

**Issue by AlerantAppNGIN** [RestComm/jss7#88]
Topic: Pulling map specific implementation and fixes from Appngin fork
Content:
  - XML serialization of ATI response.
  - ArrayListSerializingBase fixes: Fix for possible OutOfMemoryError: if the parsed XML list contains any other element
      than the one expected, we now throw an exception. Previously, the class would get stuck
      in an infinite loop filling up the list with null values, because xml.hasNext() would
      always return true and xml.get(name,class) would return null on any other element name
      and not advance the xml stream.
  - Add value range check to CUGIndexImpl

**Comment by vetss** [comment]
1) I have added following commits into master and netty-2 branches after your update:
https://github.com/RestComm/jss7/commit/8ae2307b7d973b989cfb8e9191ccf4d909a0c408
https://github.com/RestComm/jss7/commit/c163e53459b4a4e9633dc121c8a5a95f75121b7d
https://github.com/RestComm/jss7/commit/efbe3c335177fdef445da74bdcbf4b4071371ca0

Thank you for your work.

2) When we implement some XML serializing for MAP / CAP promitives we implement also XML serializing of all lower level sub primitives (even if you are not oing to use some of them). This is mandatory in order to avoid of messing in staff what is implememted and what is not.
Your update for this issue does not cover some primitives. I have created a separate issue for it:
https://github.com/RestComm/jss7/issues/99

3) When we implement some XML serializing we need to add extra unit tests for implemeted modules. There are many examples of it in implemented primitives. I have created (the same) issue for it:
https://github.com/RestComm/jss7/issues/99

4) please read the manual "https://github.com/RestComm/parent/wiki/ContributeToMobicents#Code_formatting" - chapter "Code formatting" - this chapter explains how make code formatting uniform. Please follow it.
