### ISSUE TITLE
M3UA DUNA, DAVA handling

### ISSUE THREAD

**Issue by AlerantAppNGIN** [RestComm/jss7#94]
Type: fix, new feature
Description:
There is a bug when handling incomming DAVA messages MTP-PAUSE is sent to user layer instead of MTP-RESUME.
In production telecommunication network it is possible to get "false" DUNA messages from an STP. By false I mean that the end point is reachable for our system using other routes. If we got a "false" DUNA message the M3UA layer is send an MTP-PAUSE to the upper layer the end point will be banned. If our application is not dependent of this DUNA,DAVA messages there should be a way to ignore them.

**Comment by vetss** [comment]
Hello @AlerantAppNGIN,

thanks for your update.

1) you are saying for DAVA and DUNA messages in the issue description but the update is only for DUNA case.

2) I do not have much experiense to described by you case so let you go ahead with your issue if you are sure.

3) in order to accept it we need that:
- "old behavoiur" is the default default behaviour
- we use SS7 style - for that we have to introduce an extra option at the m3ua stack level like:
boolean M3UAManagement.isMtpPauseOnDuna();
void M3UAManagement.setMtpPauseOnDuna(boolean value);
- we need to add a clear description in the manual like "if we set the option MtpPauseOnDuna to true then m3ua stack will do so and so ......., if not then ................". You can provide the text and I can add it into a manual
- m3ua stack persist options and we need to add a persistanse finctionality for a new option and also CLI / GUI for it. If you are not very sure for this step, we can postpone this step as an issue for future.

**Comment by vetss** [comment]
Close by lack of activity
