### ISSUE TITLE
TCAP dialog id generation in TCAPProviderImpl

### ISSUE THREAD

**Issue by AlerantAppNGIN** [RestComm/jss7#97]
Type: Fix or Enhancment
Description: TCAP Dialog ID generation in TCAPProviderImpl need to be refactored to meet performance goals.

**Comment by vetss** [comment]
Hello @AlerantAppNGIN,

the optimization of TCAP stack is an important task and we have to make it in a proper way.

You suggest to use ConcurrentHashMap (we reuse now javolution's FastMap). Do you know what will be a productivity of ConcurrentHashMap in case of many concurent dialogs if we have like >10000 or even >100000 concurent dialogs ? FastMap says that the access time to it does not increase dramatically when the increasing of a collection memebers count encrease (unlike ConcurrentHashMap). On the other side I am not very sure that FastMap supports a real concurency without external synchronizing even if we use it as in "shared()" mode.
Do you have any good experiense of which option is better for outr case.

As for your concrete update I can leave following comments:
1) curDialogId - it will go behind DialogIdRangeEnd. This is an issue because we need to use for some installation the definite TCAP dialog id range. (This is my be the biggest issue (: )
2) I guess "getNextSeqControl()" is able to return a value > 255, but I guess we can easily fix it
3) for previewMode we definitely need another implementation of getAvailableTxId() without DialogIdRangeStart / DialogIdRangeEnd
4) in the netty-2 branch we need to make some extra updates (it has more implemented staff) + we have also TCAP-ANSI

We may be need to arrange some discussion of how can we refactor the code and may be start with a design proposals.

**Comment by jaimecasero** [comment]
I dont see where the current id generation mechanism based in simple sequence limited by a range is a performance overhead (any particular benchmark to show this as a big system-wide bottleneck). 

I can see the sequence needs to be synchronizied at stack level. We could potentially create sequence per thread using ThreadLocal vars, and including the thread Id somehow to prevent collisions?

**Comment by deruelle** [comment]
Why don't we reuse an AtomicLong for the sequence that guarantees concurrent access ?

**Comment by vetss** [comment]
A comment from @jaimecasero :

I can see the sequence needs to be synchronizied at stack level. We could potentially create sequence per thread using ThreadLocal vars, and including the thread Id somehow to prevent collisions?. Similar to UUID generation

**Comment by jaimecasero** [comment]
@vetss  I hope you are familiar with Java ThreadLocal vars. Based on that, and assuming each Thread in a JVM has a different Id, we could potentially generate a dialog Id based on threadId+threaLocalSequence (thus preventins id collissions on different threads).

Another approach would be to split the initial configured range of dialogIds into the different threads, so the threadLocalSequence follows a subRange of the original one per Thread (this way we prevent different threads to generate the same dialogId). This needs to be setup during stack initialization, and assumes the dialogId is assigned in the context of the configured threadPool... 

Either way seeks to remove thread contention on dialogId generation, which maybe a big gain for the overall system...

**Comment by vetss** [comment]
TCAP dialogId is a 4-byte value + we may have some restrictions of a range of those values (like it may be 0-2000000 for this concrete stack if we treated that 4-bytes value as Integer). We need to discover your idea but can you comment how can we reuse "ThreadLocal vars" for this (may be some example for our ranges case) ?

**Comment by vetss** [comment]
@jaimecasero , thanks for your comment

Not sure that we can "generate a dialog Id based on threadId+threaLocalSequence" because we do not have big enouph range of available dialog Id ranges.

As for now (in current threading) any inexpected thread (from JSS7 user side) my request a new dialogId. I am not sure therefor we can assign a subrange to all possible threads at the starting time. Althow this idea may be usefull if we switch to event-driving threading model.

As for now we can only reguister any thread that wants to get a dialogId at the run-time (not at the initiatinfg time)...

**Comment by deruelle** [comment]
Why not use AtomicInteger and keep things simple and lockfree ? 

We can build a DialogSequencer utility class wrapping AtomicInteger and insuring that the value never cross 20000000 and if so goes back to 0

**Comment by jaimecasero** [comment]
@deruelle i guess the question is the performance on id generation. AtomicInteger will work, but it iwll intorduce a system/stack lock everytime an id needs to be generated.

Currently the generateId logic is protected by a sync section using the dialog map as monitor object https://github.com/RestComm/jss7/blob/master/tcap/tcap-impl/src/main/java/org/mobicents/protocols/ss7/tcap/TCAPProviderImpl.java#L282

**Comment by deruelle** [comment]
@jaimecasero AtomicInteger is lock free at Java level only at CPU level http://ashkrit.blogspot.fr/2014/02/atomicinteger-java-7-vs-java-8.html and will only get better with newer JDKs. I would recommend using a simple approach of using JDK utility classes and see how it performs. It would save us probably a lot of headaches in the future. Also the implementation of DialogSequencer could potentially be pluggable so that people interested to contribute better performing solutions can potentially do so.

Premature optimization is usually a source of evil and we noticed it in RMS by trying to reimplement JDK classes at the time.

**Comment by jaimecasero** [comment]
@deruelle  agree atomic classes will deliver best possible performance for a lock approach ( since the lock is implemented at HW level). I was elaborating on potential lock-free solutions (again this is possible using a threadpool which already introduce thread contention, but i guess that is already there, is just taking advantage of this thread model...)

Again whether we have a performance overhead on id generation or not should be supported by proper bechmark. 

On the particular case here https://github.com/RestComm/jss7/blob/master/tcap/tcap-impl/src/main/java/org/mobicents/protocols/ss7/tcap/TCAPProviderImpl.java#L280 I can see we are using a sync section using the main dialog data structure (which is stack/system level). The section seems to be necessary becuase once you get the next id, you double check there is no existing dialog with that id. So, the overhead doesnt really comes from the id generation itself, but how to verify the id is actually free, and how different datastructures are coordianted to provide consistent behavior...

**Comment by vetss** [comment]
1) for a possibility of assigning of dialogId ranges for threads I think it is not achivable now because of threading model we use and the fact that we do not usually have big enouph dialogIds range because of dialogId nature. Let's postpone this topic for new threading model design when we will be able to implement it

2) For  https://github.com/RestComm/jss7/blob/master/tcap/tcap-impl/src/main/java/org/mobicents/protocols/ss7/tcap/TCAPProviderImpl.java#L280
We have two issues here:
a) dialogId assigning
b) locking of "dialogs" collection for writing
These are different tasks and are put together only because they come one by one this code part.
Task a) may be solved by AtomicInteger if the suggested by Jean solution for the case of a limited dialogId range works.
For task b) we have issue #110 .

**Comment by vetss** [comment]
Hello @AlerantAppNGIN @jaimecasero @deruelle 

Thanks for your suggestions for performanse improvements and provided PR. I have committed updates - see comments in https://github.com/RestComm/jss7/issues/110. All updates are committed into master branch.

Feel free to check / test updatates to understand if I have not missed anything important.
